language: node_js
node_js:
- '10'
dist: trusty
cache: 
  directories:
    - node_modules
    - .firebase
branches:
  only:
  - master
script:
# - npm run deploy -- --token $FIREBASE_TOKEN
- npm run deploy
