language: node_js
node_js:
- '10'
dist: trusty
cache: 
  yarn: true
  directories:
    - node_modules
    - .firebase
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
branches:
  only:
  - master
before_script:
# Enable user namespace cloning
- "sysctl kernel.unprivileged_userns_clone=1"
# Launch XVFB
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- npm install -g firebase-tools
script:
- npm run deploy -- --token $FIREBASE_TOKEN
